version: '2.0'
services:
  # env_file: Ansible-ELK-Stack/elk.config
  mongo:
    image: docker.io/mongo:4.0
    container_name: mongo
    restart: always
    environment:
      - COMPANY=NTT
    volumes:
        - mongo:/data/db
    networks:
      - fabmedical
    ports:
      - 27017:27017

  content-init:
    image: fabmedicalntt.azurecr.io/content-init:1.0.1
    container_name: content-init
    restart: always
    environment:
      - COMPANY=NTT
      - MONGODB_CONNECTION=mongodb://mongo:27017/contentdb
    networks:
      - fabmedical

  content-api:
    image: fabmedicalntt.azurecr.io/content-api:1.0.1
    container_name: content-api
    restart: always
    environment:
      - COMPANY=NTT
      - MONGODB_CONNECTION=mongodb://mongo:27017/contentdb
    networks:
      - fabmedical
    ports:
      - 3001:3001

  content-web:
    image: fabmedicalntt.azurecr.io/content-web:1.0.1
    container_name: content-web
    restart: always
    environment:
      - COMPANY=NTT
      - CONTENT_API_URL=http://content-api:3001
    networks:
      - fabmedical
    ports:
      - 3000:3000
    
networks:
  fabmedical:

volumes: # volume แบบใช้ในตัว dcoker machine ให้จัดการเอง
  mongo:
    driver: local