# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  # ดู config จาก service connection
  dockerRegistryServiceConnection: 'fabmedicalredhatlin'
  imageRepository: 'content-web'
  containerRegistry: 'fabmedicalntt.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  commitMessage: '$(Build.SourceVersionMessage)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  # build pool จาก scale set กดผ่าน gui
  name: build


steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    
    - task: CmdLine@2
      displayName: Replace Environment Variable
      inputs:
        script: |
          sed -i "s/IMAGE_BUILD_ID/$(tag)/g" content-web.yaml
          sed -i "s/ENV_CHANGE_CAUSE_MESSAGE/[IMAGE] $(tag) - $(commitMessage)/g" content-web.yaml
    
    - task: KubernetesManifest@0
      displayName: Deploy Kubernetes
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'deploy-default-namespace'
        namespace: 'default'
        manifests: 'content-web.yaml'